# Generated by Django 5.0.1 on 2024-02-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='img',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
    ]
