# Generated by Django 5.0.1 on 2024-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_img_avatar_imagen_rename_usuario_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
